/**
 * RFC 9457 – Problem Details for HTTP APIs
 * @see https://www.rfc-editor.org/rfc/rfc9457
 */
export interface ProblemDetail {
  /** URI reference that identifies the problem type. */
  type: string;

  /** Short, human-readable summary of the problem type. */
  title: string;

  /** HTTP status code generated by the origin server. */
  status: number;

  /** Human-readable explanation specific to this occurrence. */
  detail?: string;

  /** URI reference that identifies the specific occurrence. */
  instance?: string;

  /** Extension members are permitted by the spec. */
  [key: string]: unknown;
}
